### ISSUE TITLE
Query checking does not detect closest stateful ancestor

### ISSUE THREAD

**Issue by aeberts** [holyjak/fulcro-troubleshooting#1]
The warning for queries not being joined to a stateful ancestor does not appear to check it's nearest ancestors and issues a spurious warning for the following code:

https://github.com/aeberts/fulcro-template/blob/fc81a18d8ec55efac29fb89c9abb6649d4825360/src/main/app/ui/root.cljs

Warning text for reference: "The query of app.ui.root/TodoItem should be joined into the one of its stateful ancestor app.ui.root/Root (nil). Something like: `{:some-prop (comp/get-query app.ui.root/TodoItem)}`.

**Comment by aeberts** [comment]
Image for reference:

<img width="1106" alt="Screen Shot 2021-03-09 at 9 23 26 AM" src="https://user-images.githubusercontent.com/571576/110514298-04f05b80-80bc-11eb-817d-af6b6889449e.png">

**Comment by holyjak** [comment]
I see that the component joining `TodoItem` is `ListItem` but at the same time, in its body, it does not map `ui-todo-item` but `ui-todo-item`.

The warning you get is likely from https://github.com/aeberts/fulcro-template/blob/fc81a18d8ec55efac29fb89c9abb6649d4825360/src/main/app/ui/root.cljs#L83

I see that the Root's query joins ListItem which joins ToodItem but at the same time the parent of ToodItem is the Root itself, not ListItem so something is fishy here...

**Comment by aeberts** [comment]
So this gets back to the question that I had previously which is "What do you do when your UI model and your data model diverge?" (as in this case). In the data model, ToDoItem is nested in ListItem (i.e. Lists "contain" Todos). However in the UI we have two sibling panes which are side by side (Lists on the left and Todos on the right). The UI model does not match the data model - what's the approach in this case?

**Comment by holyjak** [comment]
Make Root have 2 kids, Lists and Todos. TODOS are parameterized by the selected list idm

**Comment by holyjak** [comment]
Closing as I think we came to the conclusion that the problem was in the code, not the tool. Correct me if I am mistaken.

**Comment by aeberts** [comment]
Yes, I agree. Ok to close this issue.
