### ISSUE TITLE
fulcro-troubleshooting breaks fulcro-inspect when goog.DEBUG set to `false`

### ISSUE THREAD

**Issue by aeberts** [holyjak/fulcro-troubleshooting#5]
Hey Jakub!

fulcro-troubleshooting appear to break fulcro-inspect and the element dom picker when using fulcro-troubleshooting with `goog.DEBUG` set to `false` in shadow-cljs.edn. 

When goog.DEBUG is set to `false`, fulcro-inspect shows the `no app connected` message.

To explore the issue on your machine, clone the following repo and try running the fulcro-inspect extension:

https://github.com/aeberts/minimalist-fulcro-template-backendless

Happy to help debug if you're not able to reproduce on your end.

all the best,
Alex

**Comment by holyjak** [comment]
@aeberts you link to https://github.com/aeberts/minimalist-fulcro-template-backendless/blob/e23951a40eec3bc8df879b166e09dc674f097bbd/shadow-cljs.edn#L17 which has `goog.DEBUG true` Perhaps you changed that after submitting this issue and it was false in a prev. version?

**Comment by holyjak** [comment]
So the thing is that Fulcro Inspect itself requires DEBUG to be true. It has nothing to do with fulcro-troubleshooting. But you might be interested in #6 .

**Comment by aeberts** [comment]
Interesting that fulcro-inspect requires `goog.DEBUG` to be `true`. 

Fulcro-inspect appears to work if I remove `:closure-defines {goog.DEBUG true}` from the `:main` build of `shadow-cljs.edn` file completely. 

So, it seems we have the following cases:
goog.DEBUG missing = fulcro inspect is enabled
{goog.DEBUG true} = fulcro inspect enabled 
{goog.DEBUG false} = fulcro inspect disabled

Maybe that should be added to the fulcro-inspect README.md? (https://github.com/fulcrologic/fulcro-inspect)

**Comment by holyjak** [comment]
Because it is true by default when you run shadow-cljs watch. Only false when you run release.

**Comment by aeberts** [comment]
re: `shadow-cljs watch` - Ah, I see. I wasn't aware of that. I was using the `{goog.DEBUG true | false}` to enable or disable fulcro-troubleshooting. This can be useful when you're lining up interface elements but you still have `:query` , `:ident` or `:initial-state` errors with your component hierarchy and you want to temporarily disable fulcro-troubleshooting.

**Comment by holyjak** [comment]
An easier way of disabling is NOT adding its render middleware to fulcro-app
