### ISSUE TITLE
f-trbl's render-middleware breaks Fulcro Inspect's Element tab - cannot pick an elm

### ISSUE THREAD

**Issue by holyjak** [holyjak/fulcro-troubleshooting#6]
With the middleware added, Pick Element does not detect the component as I hover over it. //cc @aeberts

**Comment by holyjak** [comment]
Update: It is caused by wrapping the component in error-boundary. If I remove that then element picker works fine.

**Comment by holyjak** [comment]
FYI the latest version has a workaround, see the README and/or this commit 03a5fc5ac8fda5fd81a6b96bfdaa5ce8f3bdb1fa

**Comment by aeberts** [comment]
Thanks - trying it out now. Will let you know what I find.

**Comment by holyjak** [comment]
The cause is explored in fulcrologic/fulcro#495

**Comment by awkay** [comment]
We merged a PR for fulcrologic/fulcro#495. Did that not fix this?

**Comment by holyjak** [comment]
It did. Thx for the reminder!
